version: '3.9'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    networks:
      - logger
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    container_name: dynamodb-admin
    networks:
      - logger
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

# networks:
#     external: true
#     name: logger

networks:
  logger:
    name: logger
    external: true